version: "3.7"

services:
  nginx:
    image: nginx
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf 

  threetwo:
    build:
      context: .
    image: frishi/threetwo
    container_name: threetwo-ui
    ports:
      - "8050:8050"
      - "3050:3050"
    networks:
      - proxy

  comicvineapi:
    build:
      context: https://github.com/rishighan/comicvine-service.git
    image: frishi/comicvine-service
    container_name: comicvine-api
    ports:
      - "3080:3080"
    environment:
      SERVICES: api
    env_file: comicvine-service.env
    depends_on:
      - nats
    networks:
      - proxy

  comicvine:
    build:
      context: https://github.com/rishighan/comicvine-service.git
    image: frishi/comicvine-service
    container_name: comicvine-service
    environment:
      SERVICES: comicvine 
    env_file: comicvine-service.env
    networks:
      - proxy
  
  importapi:
    build:
      context: https://github.com/rishighan/threetwo-import-service.git
    image: frishi/threetwo-import-service
    container_name: threetwo-import-api
    ports:
      - "3000:3000"
    environment:
      SERVICES: api
    env_file: threetwo-import-service.env
    depends_on:
      - nats
    networks:
      - proxy
  
  import:
    build:
      context: https://github.com/rishighan/threetwo-import-service.git
    image: frishi/threetwo-import-service
    container_name: import 
    environment:
      SERVICES: import 
    env_file: threetwo-import-service.env
    networks:
      - proxy
  
  imagetransformation:
    build:
      context: https://github.com/rishighan/threetwo-import-service.git
    image: frishi/threetwo-import-service
    container_name: image-transformation 
    environment:
      SERVICES: imagetransformation 
    env_file: threetwo-import-service.env
    networks:
      - proxy

  mongodb:
    image: 'bitnami/mongodb:latest'
    container_name: mongodb
    networks:
      - proxy
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

  nats:
    image: nats:2
    container_name: transporter
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  mongodb_data:
    driver: local

