version: "3.3"

services:
  threetwo:
    build:
      context: .
      network: host
    image: frishi/threetwo
    container_name: threetwo-ui
    env_file: ./docker-compose.env
    ports:
      - "8050:8050"
      - "3050:3050"
      - "8051:8051"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - rabbitmq 
      - db
      - nginx
      - importapi
      - import
      - imagetransformation
    networks:
      - proxy

  comicvineapi:
    build:
      context: https://github.com/rishighan/comicvine-service.git
      network: host
    image: frishi/comicvine-service
    container_name: comicvine-api
    ports:
      - "3080:3080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SERVICES: api
    env_file: ./docker-env/comicvine-service.env
    volumes:
      - ./userdata:/comicvine-service/userdata
    depends_on:
      - nats
    networks:
      - proxy

  comicvine:
    build:
      context: https://github.com/rishighan/comicvine-service.git
      network: host
    image: frishi/comicvine-service
    container_name: comicvine-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SERVICES: comicvine 
    volumes:
      - ./userdata:/comicvine-service/userdata
    env_file: ./docker-env/comicvine-service.env
    networks:
      - proxy
  
  importapi:
    build:
      context: https://github.com/rishighan/threetwo-import-service.git
      network: host
    image: frishi/threetwo-import-service
    container_name: threetwo-import-api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    environment:
      SERVICES: api
    env_file: ./docker-env/threetwo-import-service.env
    volumes:
      - ./userdata:/threetwo-import-service/userdata
      - ./comics:/threetwo-import-service/comics.
    depends_on:
      - nats
      - db
    networks:
      - proxy
  
  import:
    build:
      context: https://github.com/rishighan/threetwo-import-service.git
      network: host
    image: frishi/threetwo-import-service
    container_name: import
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: 
      - db
      - nats
    environment:
      SERVICES: import 
    volumes:
      - ./userdata:/threetwo-import-service/userdata
      - ./comics:/threetwo-import-service/comics
    env_file: ./docker-env/threetwo-import-service.env
    networks:
      - proxy
  
  imagetransformation:
    build:
      context: https://github.com/rishighan/threetwo-import-service.git
      network: host
    image: frishi/threetwo-import-service
    container_name: image-transformation
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./userdata:/threetwo-import-service/userdata
      - ./comics:/threetwo-import-service/comics
    depends_on: 
      - db 
      - nats
    environment:
      SERVICES: imagetransformation 
    env_file: ./docker-env/threetwo-import-service.env
    networks:
      - proxy

  db:
    image: 'bitnami/mongodb:latest'
    container_name: database
    networks:
      - proxy
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

  nats:
    image: nats:2
    container_name: transporter
    networks:
      - proxy
  
  nginx:
    image: nginx
    container_name: reverse-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./proxy.conf
        target: /etc/nginx/conf.d/default.conf
  
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    container_name: queue
    environment:
      RABBITMQ_USERNAME: 'user'
      RABBITMQ_PASSWORD: 'bitnami'
    ports:
      - "5672:5672"
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  mongodb_data:
    driver: local

